title: Shivani Sen
tagline: Agile Practitioner & Transformation Leader
description: My Agile journey, certifications, thoughts, and more.
baseurl: "/Shivani-Sen"
url: "https://senshiv.github.io"

remote_theme: cotes2020/jekyll-theme-chirpy

lang: en
timezone: Asia/Kolkata

github:
  username: senshiv

theme_mode: light  # or dark / auto

# Navigation bar tabs
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-include-cache
