# Site settings
title: "Shivani Sen"
description: "Agile Practitioner & Transformation Leader"
#theme: jekyll-theme-chirpy
remote_theme: cotes2020/jekyll-theme-chirpy
baseurl: "/Shivani-Sen"
url: "https://senshiv.github.io"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives

# Optional: baseurl, url, etc.
