# Site settings
title: "Shivani Sen"
description: "Agile Practitioner & Transformation Leader"
#theme: jekyll-theme-chirpy
remote_theme: cotes2020/jekyll-theme-chirpy

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme

# Optional: baseurl, url, etc.
