source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-remote-theme"
gem "webrick", "~> 1.7"
