name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install compatible Bundler
        run: gem install bundler -v 2.4.19

      - name: Install dependencies
        run: bundle _2.4.19_ install --path vendor/bundle

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
